import type { RawLot } from "./types";

export const DEMO_LOTS: RawLot[] = [
  {
    source: "demo",
    lotUrl: "#",
    title: "14k Gold Diamond Pendant Necklace",
    location: "Hartford, CT",
    shippingMode: "shippable",
    currentBid: 85,
    currency: "USD",
    timeRemainingSeconds: 3600 * 6,
    watchlistCapturedAt: new Date().toISOString(),
  },
  {
    source: "demo",
    lotUrl: "#",
    title: "Matco Tools Socket Set Assortment",
    location: "Bridgeport, CT",
    shippingMode: "pickup_only",
    currentBid: 40,
    currency: "USD",
    timeRemainingSeconds: 3600 * 30,
    watchlistCapturedAt: new Date().toISOString(),
  },
  {
    source: "demo",
    lotUrl: "#",
    title: "Assorted Mystery Jewelry Lot",
    location: "New Haven, CT",
    shippingMode: "shippable",
    currentBid: 25,
    currency: "USD",
    timeRemainingSeconds: 3600 * 48,
    watchlistCapturedAt: new Date().toISOString(),
  },
  {
    source: "demo",
    lotUrl: "#",
    title: "Mid-century Modern Desk Lamp",
    location: "Stamford, CT",
    shippingMode: "shippable",
    currentBid: 15,
    currency: "USD",
    timeRemainingSeconds: 3600 * 12,
    watchlistCapturedAt: new Date().toISOString(),
  },
  {
    source: "demo",
    lotUrl: "#",
    title: "Ford Mustang Instrument Cluster",
    location: "Waterbury, CT",
    shippingMode: "shippable",
    currentBid: 95,
    currency: "USD",
    timeRemainingSeconds: 3600 * 72,
    watchlistCapturedAt: new Date().toISOString(),
  },
  {
    source: "demo",
    lotUrl: "#",
    title: "Vintage Vinyl Record Collection Beatles",
    location: "Norwalk, CT",
    shippingMode: "shippable",
    currentBid: 20,
    currency: "USD",
    timeRemainingSeconds: 3600 * 18,
    watchlistCapturedAt: new Date().toISOString(),
  },
];
